language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
# only add the two lines below if you need wkhtmltopdf for your tests
#    sources:
#      - pov-wkhtmltopdf
#    Search your sources alias here:
#      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      # for aeroo
      - cups
      - libcups2-dev
      # FE
      - python-dev
      - swig
      - libffi-dev
      - libssl-dev
      - python-m2crypto
      - python-httplib2
#     Search your packages here:
#       https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
#      - wkhtmltopdf  # only add if needed and check the before_install section below

# set up an X server to run wkhtmltopdf.
#before_install:
#  - "export DISPLAY=:913.0"
#  - "sh -e /etc/init.d/xvfb start"

env:
  global:
  - VERSION="13.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  # This line contains the encrypted transifex password
  # To encrypt transifex password, install travis ruby utils with:
  #   $ gem install travis --user-install
  # and use:
    # $ travis encrypt TRANSIFEX_PASSWORD=your-password -r owner/project
  - secure: FECLL5cJ3lS4IiDjg+6/Jw6dQkQCqkdYQnUJgYxG5+9BqDTnO64YNHcq1dRrd8Z6aK0FupVZN+ZzJn8emQb8t35yQHHPQxFEgSrn9Oo1s93g9/2uG/0hRwMOgQ4VwFr9b6eCoxhKQiigIBUdTCBf88SR7qnZDuT5/vpRnRt5+IjLfssmjLawg6S9L8btErYV5IMAbu5E/HeHElVUg5otgl0p87bHAU3lYGSJOdUWQhnP2rG+n0oH3CdhQh1Y0tufkJ/1mSDtSmJSim35P5IMiokDbMyIu6vEwMlOs+TLu5oMJbvxxE5ukPBVsUi7On7K35KXomq7nPkHuQVZHjf4MDBcR7cfscfCiBMpduokpNqPOtM+Pdi/mBvNJg/gGjBXCid97SAMP04MTidioiZrWss1AABrwPKXQjtwRWylOT2XRYj/vZm1xGwBsNSjo+QkpHFs6lt8OHxwPTCBlATm2dzT8EZujPe18bWSEhOewpZlKfR7ehlWEybTNHXaYfNwXwTdurDOzSdyzzzE4K6TIq2P0hjmeXQSPzpi/sR7n5Pq1csFHC1Tn7o7872YpzS2EXy4hQ/82/DIIubKYjWX9ScwkODB4X/ak9NB4SnATTgPx2WktgZCAS/d9b6LzXNzpi0j7uw4YjENd9RDCnqmXiFM6kj63On9VT5g6UcPriQ=
  # Use the following lines if you need to manually change the transifex project slug or/and the transifex organization.
  # The default project slug is owner-repo_name-version (with dash in the version string).
  # The default organization is the owner of the repo.
  # The default fill up resources (TM) is True.
  # The default team is 23907. https://www.transifex.com/organization/oca/team/23907/
  # - TRANSIFEX_PROJECT_SLUG=
  # - TRANSIFEX_FILL_UP_RESOURCES=
  - TRANSIFEX_ORGANIZATION='adhoc'
  - TRANSIFEX_TEAM='46451'

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"


install:
  - git clone --depth=1 https://github.com/ingadhoc/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  # if we are on TESTS then we copy this modules because if not account is pre-nstalled an it launches l10n_ar_chart installation, and then later on l10n_ar_chart re-install we have errors (native odoo errors)
  # running test with account already installed (i also happends with odoo default modules)
  # - if [ "${TESTS}" == "1"  ]; then mv ~/odoo-13.0/addons/account ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/odoo-13.0/addons/account_cancel ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/odoo-13.0/addons/account_invoicing ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/dependencies/ingadhoc-account-financial-tools/account_document ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/dependencies/ingadhoc-account-financial-tools/account_debt_management ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/dependencies/ingadhoc-account-financial-tools/account_financial_amount ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/dependencies/ingadhoc-account-payment/account_check ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/dependencies/ingadhoc-account-payment/account_withholding ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/dependencies/ingadhoc-account-payment/account_withholding_automatic ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/dependencies/ingadhoc-account-payment/account_payment_group ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/dependencies/ingadhoc-account-payment/account_payment_fix ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/dependencies/ingadhoc-account-financial-tools/account_fix ~/build/ingadhoc/odoo-argentina; fi
  # - if [ "${TESTS}" == "1"  ]; then mv ~/dependencies/account-financial-tools/currency_rate_update ~/build/ingadhoc/odoo-argentina; fi

script:
  - travis_run_tests

after_success:
  # enable aeroo docs conversion
  - if [[ "${OCA_RUNBOT}" == "1" ]]; then psql openerp_test -c "INSERT INTO ir_config_parameter (key, value) VALUES ('aeroo.docs_host', 'runbot.adhoc.com.ar'), ('aeroo.docs_port', '8989'), ('aeroo.docs_enabled', 'True')"; fi
  - travis_after_tests_success
